/**
 * Courier – game data (config, content, events).
 * Load before main game script. Exposes window.CourierData.
 */
(function () {
  "use strict";

  /* Job catalog: id, who, name, dist, seq, repeat, fbTopic (feedback template topic) */
  var JOB_CATALOG_RAW = [
    /* Sam Patel (20) */
    { id: "sam_01", who: "Sam Patel", name: "Hot food drop", dist: 2.0, seq: 1, repeat: true, fbTopic: "that hot drop" },
    { id: "sam_02", who: "Sam Patel", name: "Parcel run", dist: 3.5, seq: 1, repeat: true, fbTopic: "the parcel" },
    { id: "sam_03", who: "Sam Patel", name: "Groceries", dist: 4.2, seq: 1, repeat: true, fbTopic: "the groceries" },
    { id: "sam_04", who: "Sam Patel", name: "Fragile item", dist: 5.0, seq: 1, repeat: false, fbTopic: "the fragile item" },
    { id: "sam_05", who: "Sam Patel", name: "Rush SLA", dist: 6.0, seq: 2, repeat: true, fbTopic: "the rush SLA" },
    { id: "sam_06", who: "Sam Patel", name: "Late rent env", dist: 2.4, seq: 2, repeat: false, fbTopic: "the rent envelope" },
    { id: "sam_07", who: "Sam Patel", name: "Urgent drive", dist: 6.1, seq: 2, repeat: true, fbTopic: "the hard drive" },
    { id: "sam_08", who: "Sam Patel", name: "Council docs", dist: 3.7, seq: 2, repeat: true, fbTopic: "the council docs" },
    { id: "sam_09", who: "Sam Patel", name: "Legal bundle", dist: 5.4, seq: 3, repeat: true, fbTopic: "the legal bundle" },
    { id: "sam_10", who: "Sam Patel", name: "Press pass", dist: 4.4, seq: 3, repeat: false, fbTopic: "the press pass" },
    { id: "sam_11", who: "Sam Patel", name: "Lab sample", dist: 5.9, seq: 3, repeat: true, fbTopic: "the lab sample" },
    { id: "sam_12", who: "Sam Patel", name: "Film reel", dist: 6.6, seq: 3, repeat: false, fbTopic: "the film reel" },
    { id: "sam_13", who: "Sam Patel", name: "Vintage vinyl", dist: 2.5, seq: 4, repeat: true, fbTopic: "the vinyl swap" },
    { id: "sam_14", who: "Sam Patel", name: "Wristbands", dist: 4.8, seq: 4, repeat: true, fbTopic: "the wristbands" },
    { id: "sam_15", who: "Sam Patel", name: "Passport return", dist: 6.9, seq: 4, repeat: false, fbTopic: "the passport" },
    { id: "sam_16", who: "Sam Patel", name: "Theatre keys", dist: 4.0, seq: 4, repeat: true, fbTopic: "those keys" },
    { id: "sam_17", who: "Sam Patel", name: "Knife set", dist: 3.1, seq: 5, repeat: true, fbTopic: "the knife set" },
    { id: "sam_18", who: "Sam Patel", name: "Sash parts", dist: 5.8, seq: 5, repeat: false, fbTopic: "the window parts" },
    { id: "sam_19", who: "Sam Patel", name: "Phone return", dist: 3.6, seq: 5, repeat: true, fbTopic: "that phone" },
    { id: "sam_20", who: "Sam Patel", name: "Bike lock", dist: 2.2, seq: 5, repeat: true, fbTopic: "the lock rescue" },

    /* Rosa Klein (20) */
    { id: "rosa_01", who: "Rosa Klein", name: "VIP sushi", dist: 3.2, seq: 1, repeat: true, fbTopic: "the sushi" },
    { id: "rosa_02", who: "Rosa Klein", name: "Cake rescue", dist: 5.6, seq: 1, repeat: true, fbTopic: "the cake" },
    { id: "rosa_03", who: "Rosa Klein", name: "Props drop", dist: 2.7, seq: 1, repeat: true, fbTopic: "the props" },
    { id: "rosa_04", who: "Rosa Klein", name: "Do not bend", dist: 3.9, seq: 1, repeat: false, fbTopic: "the book" },
    { id: "rosa_05", who: "Rosa Klein", name: "Band merch", dist: 4.1, seq: 2, repeat: true, fbTopic: "the merch" },
    { id: "rosa_06", who: "Rosa Klein", name: "Tattoo stencil", dist: 2.1, seq: 2, repeat: true, fbTopic: "the stencil" },
    { id: "rosa_07", who: "Rosa Klein", name: "Cake topper", dist: 3.4, seq: 2, repeat: true, fbTopic: "the topper" },
    { id: "rosa_08", who: "Rosa Klein", name: "Charity box", dist: 4.7, seq: 2, repeat: false, fbTopic: "the raffle box" },
    { id: "rosa_09", who: "Rosa Klein", name: "Poster tubes", dist: 4.9, seq: 3, repeat: true, fbTopic: "the posters" },
    { id: "rosa_10", who: "Rosa Klein", name: "Lens rental", dist: 5.5, seq: 3, repeat: true, fbTopic: "the lens" },
    { id: "rosa_11", who: "Rosa Klein", name: "Studio keys", dist: 3.1, seq: 3, repeat: false, fbTopic: "studio keys" },
    { id: "rosa_12", who: "Rosa Klein", name: "Afterparty bands", dist: 4.2, seq: 3, repeat: true, fbTopic: "the bands" },
    { id: "rosa_13", who: "Rosa Klein", name: "Set list", dist: 2.0, seq: 4, repeat: true, fbTopic: "the set list" },
    { id: "rosa_14", who: "Rosa Klein", name: "Wardrobe pins", dist: 2.8, seq: 4, repeat: true, fbTopic: "wardrobe pins" },
    { id: "rosa_15", who: "Rosa Klein", name: "Makeup kit", dist: 3.6, seq: 4, repeat: false, fbTopic: "the makeup kit" },
    { id: "rosa_16", who: "Rosa Klein", name: "USB master", dist: 5.7, seq: 4, repeat: true, fbTopic: "the USB master" },
    { id: "rosa_17", who: "Rosa Klein", name: "Signed vinyl", dist: 3.8, seq: 5, repeat: false, fbTopic: "the signed vinyl" },
    { id: "rosa_18", who: "Rosa Klein", name: "Green room", dist: 2.6, seq: 5, repeat: true, fbTopic: "green room snacks" },
    { id: "rosa_19", who: "Rosa Klein", name: "Ticket stubs", dist: 3.0, seq: 5, repeat: true, fbTopic: "ticket stubs" },
    { id: "rosa_20", who: "Rosa Klein", name: "Stage pass", dist: 4.4, seq: 5, repeat: true, fbTopic: "the stage pass" },

    /* Aisha Rahman (20) */
    { id: "aisha_01", who: "Aisha Rahman", name: "Pharmacy pickup", dist: 2.8, seq: 1, repeat: true, fbTopic: "the pickup" },
    { id: "aisha_02", who: "Aisha Rahman", name: "Iguana meds", dist: 6.4, seq: 1, repeat: true, fbTopic: "the meds" },
    { id: "aisha_03", who: "Aisha Rahman", name: "Clinic forms", dist: 3.2, seq: 1, repeat: true, fbTopic: "those forms" },
    { id: "aisha_04", who: "Aisha Rahman", name: "Blood kit", dist: 4.1, seq: 1, repeat: false, fbTopic: "the kit" },
    { id: "aisha_05", who: "Aisha Rahman", name: "Lab rush", dist: 5.9, seq: 2, repeat: true, fbTopic: "the rush sample" },
    { id: "aisha_06", who: "Aisha Rahman", name: "X-ray disc", dist: 4.6, seq: 2, repeat: false, fbTopic: "the disc" },
    { id: "aisha_07", who: "Aisha Rahman", name: "Care package", dist: 3.9, seq: 2, repeat: true, fbTopic: "the package" },
    { id: "aisha_08", who: "Aisha Rahman", name: "Vaccine docs", dist: 3.4, seq: 2, repeat: true, fbTopic: "the docs" },
    { id: "aisha_09", who: "Aisha Rahman", name: "Specimen box", dist: 5.2, seq: 3, repeat: true, fbTopic: "the specimen" },
    { id: "aisha_10", who: "Aisha Rahman", name: "Allergy results", dist: 3.7, seq: 3, repeat: true, fbTopic: "the results" },
    { id: "aisha_11", who: "Aisha Rahman", name: "Dental mould", dist: 4.8, seq: 3, repeat: false, fbTopic: "the mould" },
    { id: "aisha_12", who: "Aisha Rahman", name: "Stitch kit", dist: 2.9, seq: 3, repeat: true, fbTopic: "the kit" },
    { id: "aisha_13", who: "Aisha Rahman", name: "Cold chain", dist: 6.6, seq: 4, repeat: true, fbTopic: "cold chain" },
    { id: "aisha_14", who: "Aisha Rahman", name: "Urgent referral", dist: 6.0, seq: 4, repeat: false, fbTopic: "the referral" },
    { id: "aisha_15", who: "Aisha Rahman", name: "Ward swap", dist: 4.0, seq: 4, repeat: true, fbTopic: "the ward swap" },
    { id: "aisha_16", who: "Aisha Rahman", name: "Therapy notes", dist: 3.1, seq: 4, repeat: true, fbTopic: "the notes" },
    { id: "aisha_17", who: "Aisha Rahman", name: "Consent forms", dist: 3.6, seq: 5, repeat: true, fbTopic: "consent forms" },
    { id: "aisha_18", who: "Aisha Rahman", name: "Path slides", dist: 5.8, seq: 5, repeat: false, fbTopic: "the slides" },
    { id: "aisha_19", who: "Aisha Rahman", name: "IV supplies", dist: 4.4, seq: 5, repeat: true, fbTopic: "IV supplies" },
    { id: "aisha_20", who: "Aisha Rahman", name: "Hosp keys", dist: 3.3, seq: 5, repeat: false, fbTopic: "those keys" },

    /* Tom Weaver (20) */
    { id: "tom_01", who: "Tom Weaver", name: "Office keys", dist: 2.2, seq: 1, repeat: true, fbTopic: "the keys" },
    { id: "tom_02", who: "Tom Weaver", name: "Laptop charger", dist: 3.0, seq: 1, repeat: true, fbTopic: "the charger" },
    { id: "tom_03", who: "Tom Weaver", name: "Contract copies", dist: 4.1, seq: 1, repeat: true, fbTopic: "the contracts" },
    { id: "tom_04", who: "Tom Weaver", name: "Signed NDA", dist: 3.6, seq: 1, repeat: false, fbTopic: "the NDA" },
    { id: "tom_05", who: "Tom Weaver", name: "Meeting pack", dist: 4.8, seq: 2, repeat: true, fbTopic: "the pack" },
    { id: "tom_06", who: "Tom Weaver", name: "Printer toner", dist: 2.7, seq: 2, repeat: true, fbTopic: "the toner" },
    { id: "tom_07", who: "Tom Weaver", name: "Client gift", dist: 5.0, seq: 2, repeat: false, fbTopic: "the gift" },
    { id: "tom_08", who: "Tom Weaver", name: "Board papers", dist: 5.6, seq: 2, repeat: true, fbTopic: "the board papers" },
    { id: "tom_09", who: "Tom Weaver", name: "Proto demo", dist: 6.2, seq: 3, repeat: true, fbTopic: "the demo" },
    { id: "tom_10", who: "Tom Weaver", name: "Finance pack", dist: 4.9, seq: 3, repeat: true, fbTopic: "the finance pack" },
    { id: "tom_11", who: "Tom Weaver", name: "Share cert", dist: 3.4, seq: 3, repeat: false, fbTopic: "the certificate" },
    { id: "tom_12", who: "Tom Weaver", name: "Courier samples", dist: 5.3, seq: 3, repeat: true, fbTopic: "the samples" },
    { id: "tom_13", who: "Tom Weaver", name: "Spare badge", dist: 2.6, seq: 4, repeat: true, fbTopic: "the badge" },
    { id: "tom_14", who: "Tom Weaver", name: "Server dongle", dist: 6.1, seq: 4, repeat: false, fbTopic: "the dongle" },
    { id: "tom_15", who: "Tom Weaver", name: "Audit files", dist: 5.8, seq: 4, repeat: true, fbTopic: "the audit files" },
    { id: "tom_16", who: "Tom Weaver", name: "Client minutes", dist: 3.9, seq: 4, repeat: true, fbTopic: "those minutes" },
    { id: "tom_17", who: "Tom Weaver", name: "Pitch deck", dist: 4.6, seq: 5, repeat: true, fbTopic: "the deck" },
    { id: "tom_18", who: "Tom Weaver", name: "Signed contract", dist: 5.2, seq: 5, repeat: false, fbTopic: "the contract" },
    { id: "tom_19", who: "Tom Weaver", name: "Data stick", dist: 3.3, seq: 5, repeat: true, fbTopic: "the data stick" },
    { id: "tom_20", who: "Tom Weaver", name: "Late invoice", dist: 3.8, seq: 5, repeat: true, fbTopic: "the invoice" }
  ];

  var EVENT_POOL = {
    normal: [
      { t: "Red light gamble", d: "You gun it through a late amber. Lose 6% energy.", energy: -6, mins: 0, mood: "bad" },
      { t: "Stairwell detour", d: "Lift is out. Lose 4 minutes.", energy: 0, mins: 4, mood: "bad" },
      { t: "Tailwind stretch", d: "Clear road. Gain 2 minutes.", energy: 0, mins: -2, mood: "good" },
      { t: "Loose strap", d: "Bag strap slips. Lose 3% energy and 2 minutes.", energy: -3, mins: 2, mood: "bad" },
      { t: "Quiet cut-through", d: "A calm side street. Gain 1 minute.", energy: 0, mins: -1, mood: "good" },
      { t: "Coffee queue", d: "You get stuck behind a crowd. Lose 3 minutes.", energy: 0, mins: 3, mood: "bad" },
      { t: "Helpful doorman", d: "Someone holds the door. Gain 1 minute.", energy: 0, mins: -1, mood: "good" },
      { t: "Wrong buzzer", d: "You buzz the wrong flat. Lose 2 minutes.", energy: 0, mins: 2, mood: "bad" },
      { t: "Cobbles", d: "Rattly cobbles drain you. Lose 2% energy.", energy: -2, mins: 0, mood: "bad" },
      { t: "Green wave", d: "Every light goes green. Gain 3 minutes.", energy: 0, mins: -3, mood: "good" },
      { t: "Roadworks shuffle", d: "Cones everywhere. Lose 5 minutes.", energy: 0, mins: 5, mood: "bad" },
      { t: "Unexpected shortcut", d: "A signed cut-through. Gain 2 minutes.", energy: 0, mins: -2, mood: "good" },
      { t: "Bag re-pack", d: "You re-pack on the move. Lose 1 minute, save 1% energy.", energy: 1, mins: 1, mood: "neutral" },
      { t: "Steep ramp", d: "A long ramp saps you. Lose 4% energy.", energy: -4, mins: 0, mood: "bad" }
    ],
    accident: [
      { t: "Near miss", d: "Hard brake. You wobble it out. Lose 8% energy and 3 minutes.", energy: -8, mins: 3, mood: "bad" },
      { t: "Minor spill", d: "You clip a curb. Lose 12% energy and 6 minutes.", energy: -12, mins: 6, mood: "bad" },
      { t: "Impact scare", d: "Close call with a car door. Lose 10% energy and 4 minutes.", energy: -10, mins: 4, mood: "bad" },
      { t: "Chain slip", d: "Chain slips under load. Lose 6% energy and 3 minutes.", energy: -6, mins: 3, mood: "bad" },
      { t: "Skid", d: "Painted lines in drizzle. Lose 9% energy and 2 minutes.", energy: -9, mins: 2, mood: "bad" },
      { t: "Kerb strike", d: "Wheel bangs a kerb. Lose 7% energy and 5 minutes.", energy: -7, mins: 5, mood: "bad" },
      { t: "Handlebar clip", d: "You clip a bollard. Lose 11% energy and 4 minutes.", energy: -11, mins: 4, mood: "bad" },
      { t: "Foot slip", d: "Foot slips off pedal. Lose 5% energy and 2 minutes.", energy: -5, mins: 2, mood: "bad" },
      { t: "Bag spill", d: "Something shifts. Lose 8% energy and 6 minutes.", energy: -8, mins: 6, mood: "bad" }
    ]
  };

  var PROMPT_EVENTS = [
    { t: "Shortcut sign", d: "A gated cut-through is ajar. Could save time.", energy: 0, mins: -2 },
    { t: "Dodgy alley", d: "You cut through anyway. Bad vibe. Lose time.", energy: 0, mins: 3 },
    { t: "Perfect slipstream", d: "You tuck in behind a smooth rider. Gain time.", energy: 0, mins: -2 },
    { t: "Puddle blast", d: "You hit a deep puddle. Lose energy and time.", energy: -5, mins: 2 }
  ];

  /* End-of-day random events: 0–2 per day, bias toward negatives. amt is magnitude; game applies sign. */
  var END_OF_DAY_POSITIVES = [
    { t: "Found a fiver", amt: 5 }, { t: "Lottery scratchcard", amt: 8 }, { t: "Sold old lock", amt: 12 },
    { t: "Tip from stranger", amt: 4 }, { t: "Refund (wrong order)", amt: 7 }, { t: "Cashback voucher", amt: 6 },
    { t: "Spare change in pocket", amt: 3 }, { t: "Sold phone charger", amt: 10 }, { t: "Bonus from client", amt: 15 },
    { t: "Found tenner", amt: 10 }, { t: "Lucky dip win", amt: 6 }, { t: "Returned bottle deposit", amt: 2 },
    { t: "Odd job for neighbour", amt: 14 }, { t: "Voucher in magazine", amt: 5 }, { t: "Small bet paid out", amt: 11 },
    { t: "Sold old jacket", amt: 18 }, { t: "Found coins in wash", amt: 4 }, { t: "Survey reward", amt: 8 },
    { t: "Cashback at shop", amt: 3 }, { t: "Friend paid you back", amt: 20 }, { t: "Scratchcard (small)", amt: 5 },
    { t: "Sold bike light", amt: 6 }, { t: "Overpaid change returned", amt: 7 }, { t: "Car boot sale item", amt: 9 },
    { t: "Found note on pavement", amt: 10 }, { t: "Rebate cheque", amt: 12 }, { t: "Gig payment (small)", amt: 15 },
    { t: "Sold book", amt: 4 }, { t: "Loyalty points cashed", amt: 6 }, { t: "Tip jar share", amt: 8 },
    { t: "Wrong change (in your favour)", amt: 5 }, { t: "Sold headphones", amt: 14 }, { t: "Raffle ticket win", amt: 10 },
    { t: "Pet-sit payment", amt: 12 }, { t: "Sold old shoes", amt: 8 }, { t: "Found wallet (reward)", amt: 15 },
    { t: "Market stall help", amt: 10 }, { t: "Sold vinyl", amt: 11 }, { t: "Cash gift", amt: 12 },
    { t: "Sold lamp", amt: 9 }, { t: "Competition prize", amt: 15 }, { t: "Sold plant", amt: 7 },
    { t: "Helped move (tip)", amt: 18 }, { t: "Sold mirror", amt: 8 }, { t: "Found voucher", amt: 5 },
    { t: "Sold tools", amt: 22 }, { t: "Cash in birthday card", amt: 10 }, { t: "Sold kettle", amt: 6 },
    { t: "Odd job: errand", amt: 9 }, { t: "Sold chair", amt: 15 }, { t: "Refund (duplicate)", amt: 8 },
    { t: "Sold bag", amt: 12 }, { t: "Found fiver in coat", amt: 5 }, { t: "Sold clock", amt: 7 },
    { t: "Small inheritance (relative)", amt: 25 }, { t: "Sold vase", amt: 6 }, { t: "Cashback app", amt: 4 },
    { t: "Sold shelf", amt: 11 }, { t: "Tip (delivery)", amt: 6 }, { t: "Sold picture frame", amt: 5 },
    { t: "Lucky find (car boot)", amt: 9 }, { t: "Sold blanket", amt: 8 }, { t: "Overpayment returned", amt: 7 },
    { t: "Sold mug set", amt: 6 }, { t: "Found coins (sofa)", amt: 3 }, { t: "Sold cushion", amt: 5 },
    { t: "Small freelance", amt: 20 }, { t: "Sold candle", amt: 4 }, { t: "Rebate (utility)", amt: 12 },
    { t: "Sold coaster set", amt: 3 }, { t: "Tip (carried bags)", amt: 5 }, { t: "Sold bookends", amt: 7 },
    { t: "Found note in book", amt: 8 }, { t: "Sold pen", amt: 2 }, { t: "Cash from side hustle", amt: 14 },
    { t: "Sold notebook", amt: 4 }, { t: "Lucky penny day", amt: 5 }, { t: "Sold keyring", amt: 3 },
    { t: "Refund (cancelled)", amt: 9 }, { t: "Sold umbrella", amt: 6 }, { t: "Found cash (bus)", amt: 7 },
    { t: "Sold scarf", amt: 8 }, { t: "Small dividend", amt: 10 }, { t: "Sold gloves", amt: 5 },
    { t: "Helped with flat pack", amt: 12 }, { t: "Sold hat", amt: 6 }, { t: "Cashback (card)", amt: 4 },
    { t: "Sold belt", amt: 7 }, { t: "Found coins (pocket)", amt: 2 }, { t: "Sold watch (cheap)", amt: 15 },
    { t: "Odd job: posting", amt: 8 }, { t: "Sold sunglasses", amt: 10 }, { t: "Voucher (birthday)", amt: 10 },
    { t: "Sold bag (small)", amt: 9 }, { t: "Tip (directions)", amt: 4 }, { t: "Sold wallet (old)", amt: 5 },
    { t: "Found money (park)", amt: 6 }, { t: "Sold cardigan", amt: 11 }, { t: "Refund (faulty)", amt: 8 },
    { t: "Sold jumper", amt: 10 }, { t: "Lucky day (small)", amt: 7 }, { t: "Sold trousers", amt: 12 },
    { t: "Helped neighbour", amt: 8 }, { t: "Sold shirt", amt: 7 }, { t: "Cashback (fuel)", amt: 5 },
    { t: "Sold tie", amt: 4 }, { t: "Found coins (street)", amt: 3 }, { t: "Sold socks (pack)", amt: 3 },
    { t: "Odd job: dog walk", amt: 10 }, { t: "Sold coat", amt: 18 }, { t: "Tip (held door)", amt: 2 },
    { t: "Sold dress", amt: 14 }, { t: "Rebate (insurance)", amt: 11 }, { t: "Sold boots", amt: 16 }
  ];

  var END_OF_DAY_NEGATIVES = [
    { t: "Parking fine", amt: 25 }, { t: "Dry cleaning", amt: 12 }, { t: "Phone top-up", amt: 10 },
    { t: "Inner tube", amt: 8 }, { t: "Lock replacement", amt: 18 }, { t: "Cafe (forgot lunch)", amt: 6 },
    { t: "Puncture repair", amt: 12 }, { t: "Brake pads", amt: 22 }, { t: "Chain replacement", amt: 28 },
    { t: "Parking meter", amt: 5 }, { t: "Coffee (treat)", amt: 4 }, { t: "Snack (petrol station)", amt: 5 },
    { t: "Bike service", amt: 35 }, { t: "New gloves", amt: 14 }, { t: "Waterproof spray", amt: 8 },
    { t: "Bus fare (bike broke)", amt: 6 }, { t: "Spare tube", amt: 7 }, { t: "Lunch (forgot)", amt: 9 },
    { t: "New bottle cage", amt: 6 }, { t: "Pannier repair", amt: 10 }, { t: "Lights (battery)", amt: 5 },
    { t: "Helmet (replacement)", amt: 30 }, { t: "Grip tape", amt: 4 }, { t: "Spoke repair", amt: 15 },
    { t: "New cable lock", amt: 20 }, { t: "Saddle bag", amt: 12 }, { t: "Pump (mini)", amt: 8 },
    { t: "Mudguard", amt: 11 }, { t: "Bell replacement", amt: 5 }, { t: "Reflector set", amt: 4 },
    { t: "Cat sitting fee", amt: 15 }, { t: "Vet (friend's pet)", amt: 20 }, { t: "Flowers (apology)", amt: 12 },
    { t: "Birthday card + gift", amt: 10 }, { t: "Donation (chugger)", amt: 5 }, { t: "Charity tin", amt: 3 },
    { t: "Lost bet", amt: 8 }, { t: "Subscription (forgot)", amt: 9 }, { t: "App purchase", amt: 5 },
    { t: "Bank fee", amt: 12 }, { t: "Overdraft charge", amt: 15 }, { t: "Card replacement", amt: 10 },
    { t: "Key cut", amt: 8 }, { t: "Shoe repair", amt: 14 }, { t: "Watch battery", amt: 6 },
    { t: "Dry cleaning (rush)", amt: 18 }, { t: "Laundry (coin)", amt: 5 }, { t: "Ironing service", amt: 12 },
    { t: "Postage (return)", amt: 6 }, { t: "Parcel (lost)", amt: 15 }, { t: "Printing", amt: 4 },
    { t: "Photo prints", amt: 8 }, { t: "USB stick", amt: 6 }, { t: "Phone case", amt: 10 },
    { t: "Screen protector", amt: 7 }, { t: "Charger (replace)", amt: 12 }, { t: "Earphones", amt: 15 },
    { t: "Battery pack", amt: 18 }, { t: "Adapter", amt: 8 }, { t: "Cable (spare)", amt: 5 },
    { t: "Medicine (OTC)", amt: 9 }, { t: "Plasters + antiseptic", amt: 4 }, { t: "Vitamins", amt: 11 },
    { t: "Dentist (check-up)", amt: 25 }, { t: "Optician", amt: 20 }, { t: "Prescription", amt: 9 },
    { t: "Haircut", amt: 14 }, { t: "Barber", amt: 10 }, { t: "Toiletries", amt: 8 },
    { t: "Cat food (neighbour)", amt: 6 }, { t: "Plant (replacement)", amt: 7 }, { t: "Light bulb", amt: 3 },
    { t: "Batteries (AA)", amt: 5 }, { t: "Fuse", amt: 2 }, { t: "Extension lead", amt: 12 },
    { t: "Stamps", amt: 8 }, { t: "Envelope (bulk)", amt: 4 }, { t: "Tape", amt: 3 },
    { t: "Glue", amt: 4 }, { t: "Screwdriver set", amt: 15 }, { t: "Drill bit", amt: 6 },
    { t: "Sandpaper", amt: 5 }, { t: "Paint (touch-up)", amt: 11 }, { t: "Brush", amt: 4 },
    { t: "Ladder hire", amt: 18 }, { t: "Skip (shared)", amt: 25 }, { t: "Bin bags", amt: 5 },
    { t: "Cleaning spray", amt: 4 }, { t: "Sponge", amt: 2 }, { t: "Mop", amt: 8 },
    { t: "Replacement key", amt: 35 }, { t: "Locksmith (call-out)", amt: 45 }, { t: "Spare key cut", amt: 6 },
    { t: "Window repair", amt: 22 }, { t: "Draft excluder", amt: 7 }, { t: "Thermometer", amt: 5 },
    { t: "Cat massage", amt: 18 }, { t: "Dog walker (cover)", amt: 12 }, { t: "Fish food", amt: 4 },
    { t: "Takeaway (tired)", amt: 14 }, { t: "Pizza", amt: 12 }, { t: "Kebab", amt: 8 },
    { t: "Chip shop", amt: 7 }, { t: "Meal deal", amt: 5 }, { t: "Sandwich (premium)", amt: 6 },
    { t: "Cake (treat)", amt: 4 }, { t: "Pastry", amt: 3 }, { t: "Smoothie", amt: 5 },
    { t: "Energy drink (shop)", amt: 3 }, { t: "Water (bottle)", amt: 2 }, { t: "Chewing gum", amt: 1 },
    { t: "Newspaper", amt: 2 }, { t: "Magazine", amt: 5 }, { t: "Book (paperback)", amt: 8 },
    { t: "Pen (fancy)", amt: 6 }, { t: "Notebook", amt: 4 }, { t: "Folder", amt: 3 },
    { t: "Umbrella (replace)", amt: 10 }, { t: "Gloves (lost)", amt: 8 }, { t: "Scarf (new)", amt: 12 },
    { t: "Socks (pack)", amt: 6 }, { t: "Underwear", amt: 10 }, { t: "Tights", amt: 5 },
    { t: "Shoe polish", amt: 4 }, { t: "Laces", amt: 3 }, { t: "Insoles", amt: 8 },
    { t: "Taxi (emergency)", amt: 15 }, { t: "Bus (wrong one)", amt: 4 }, { t: "Train (short)", amt: 6 },
    { t: "Parking (hospital)", amt: 12 }, { t: "Congestion charge", amt: 15 }, { t: "Toll", amt: 5 },
    { t: "Car wash", amt: 8 }, { t: "Screen wash", amt: 4 }, { t: "De-icer", amt: 5 },
    { t: "Late fee", amt: 10 }, { t: "Admin charge", amt: 8 }, { t: "Booking fee", amt: 6 },
    { t: "Delivery fee", amt: 5 }, { t: "Service charge", amt: 7 }, { t: "Tip (mandatory)", amt: 4 },
    { t: "Fine (library)", amt: 3 }, { t: "Replacement card", amt: 5 }, { t: "Membership", amt: 12 }
  ];

  window.CourierData = {
    VERSION: "1.0.44",
    WEEKLY_TARGET: 1000,
    PRICES: { drink: 12, snack: 6 },
    COSTS: { bills: 35, food: 15 },
    WEEKLY_RENT: 1000,
    SPEEDS: {
      1: { name: "very slow", mult: 0.55 },
      2: { name: "slow", mult: 0.8 },
      3: { name: "average", mult: 1 },
      4: { name: "fast", mult: 1.25 },
      5: { name: "very fast", mult: 1.55 }
    },
    ROUTES: ["Easy", "Mid", "Tricky", "Hellish"],
    QUOTES: [
      "We've had two riders drop this already. Needs doing before the deadline.",
      "Client is calling every 2 minutes. Keep it moving.",
      "Estate drop. Stairs. No lift. Don't be late."
    ],
    REQUESTORS: ["Sam Patel", "Rosa Klein", "Aisha Rahman", "Tom Weaver"],
    REPUTATION: { "Sam Patel": 7, "Rosa Klein": 8, "Aisha Rahman": 9, "Tom Weaver": 6 },
    JOB_CATALOG_RAW: JOB_CATALOG_RAW,
    EVENT_POOL: EVENT_POOL,
    PROMPT_EVENTS: PROMPT_EVENTS,
    END_OF_DAY_POSITIVES: END_OF_DAY_POSITIVES,
    END_OF_DAY_NEGATIVES: END_OF_DAY_NEGATIVES,
    SAVE_KEY: "courier_save",
    SAVE_SCHEMA: 4
  };
})();
